### ISSUE TITLE
mqforward.ini.j2

### ISSUE THREAD

**Issue by RobynWillison** [wolfeidau/gophermq-stack#1]
Should the port number here be 1883?

[mqforward-mqtt]
port = 8883

**Comment by wolfeidau** [comment]
Heya,

Great question, as per the MQTT FAQ.

> Are there standard ports for MQTT to use?
> Yes. TCP/IP port 1883 is reserved with IANA for use with MQTT. TCP/IP port 8883 is also registered, for using MQTT over SSL.

see http://mqtt.org/faq

I am a big fan of any TLS I can get for my data :lock:
